Refactored Game and Map generation
KuraiAndras/TravisGradleProjlab pull request #10
Opened 2018-03-16 19:27 UTC by KuraiAndras

2018-03-16 20:01 UTC, Kaspi95 commented on src/main/java/projlab/Game.java
> +        doLockManagement();
nyerhetünk egy keveset azon ha csak a Player.collide(box,d) végén hívjuk meg

2018-03-16 20:21 UTC, KuraiAndras commented on src/main/java/projlab/Game.java
> +        doLockManagement();
Jó kérdés. Igazából ha átrakjuk collide-ba ott nyerünk amikor a player nem tol semmit, ellenben ha a tolási sorban van valahogy egy player ami előtt még van doboz ott meg duplán fog meghívódni.

2018-03-17 10:36 UTC, Kaspi95 commented on src/main/java/projlab/Game.java
> +        doLockManagement();
Ha a Field.onStepped(Player player, Direction direction) -ben a collide true visszatéréséhez kötjük akkor nyerünk a legtöbbet.

2018-03-17 11:21 UTC, KuraiAndras commented on src/main/java/projlab/Game.java
> +        doLockManagement();
dobd vissza a pull requestet változtatás kéréssel, aztán mindjárt megcsinálom

2018-03-17 12:20 UTC, Kaspi95 requested changes
doLockManagement better in onstepps

2018-03-17 12:45 UTC, closed without merging